export const ListStatesProvincesFragment = {
"AK": "Alaska",
"AL": "Alabama",
"AZ": "Arizona",
"AR": "Arkansas",
"CA": "California",
"CO": "Colorado",
"CT": "Connecticut",
"DE": "Delaware",
"DC": "District of Columbia",
"FL": "Florida",
"GA": "Georgia",
"GU": "Guam",
"HI": "Hawaii",
"ID": "Idaho",
"IL": "Illinois",
"IN": "Indiana",
"IA": "Iowa",
"KS": "Kansas",
"KY": "Kentucky",
"LA": "Louisiana",
"ME": "Maine",
"MH": "Marshall Islands",
"MD": "Maryland",
"MA": "Massachusetts",
"MI": "Michigan",
"MN": "Minnesota",
"MS": "Mississippi",
"MO": "Missouri",
"MT": "Montana",
"NE": "Nebraska",
"NV": "Nevada",
"NH": "New Hampshire",
"NJ": "New Jersey",
"NM": "New Mexico",
"NY": "New York",
"NC": "North Carolina",
"ND": "North Dakota",
"OH": "Ohio",
"OK": "Oklahoma",
"OR": "Oregon",
"PW": "Palau",
"PA": "Pennsylvania",
"PR": "Puerto Rico",
"RI": "Rhode Island",
"SC": "South Carolina",
"SD": "South Dakota",
"TN": "Tennessee",
"TX": "Texas",
"UT": "Utah",
"VI": "U.S. Virgin Islands",
"VT": "Vermont",
"VA": "Virginia",
"WA": "Washington",
"WV": "West Virginia",
"WI": "Wisconsin",
"WY": "Wyoming",
"ZZ": "Outside U.S.",
"ON": "Ontario",
"QC": "Quebec",
"BC": "British Columbia",
"AB": "Alberta",
"MB": "Manitoba",
"SK": "Saskatchewan",
"NS": "Nova Scotia",
"NB": "New Brunswick",
"NL": "Newfoundland and Labrador",
"PE": "Prince Edward Island",
"NT": "Northwest Territories",
"NU": "Nunavut",
"YT": "Yukon",
"AGU": "Aguascalientes",
"BCN": "Baja California",
"BCS": "Baja California Sur",
"CAM": "Campeche",
"COL": "Colima",
"CHP": "Chiapas",
"CHH": "Chihuahua",
"DIF": "Distrito Federal",
"DUR": "Durango",
"GRO": "Guerrero",
"GUA": "Guanajuato",
"HID": "Hidalgo",
"JAL": "Jalisco",
"MEX": "Mexico",
"MIC": "Michoacan De Ocampo",
"MOR": "Morelos",
"NAY": "Nayarit",
"NLE": "Nuevo Leon",
"OAX": "Oaxaca",
"PUE": "Puebla",
"QUE": "Queretaro De Arteaga",
"ROO": "Quintana Roo",
"SIN": "Sinaloa",
"SLP": "San Luis Potosi",
"SON": "Sonora",
"TAB": "Tabasco",
"TAM": "Tamaulipas",
"TLA": "Tlaxcala",
"VER": "Veracruz Llave",
"YUC": "Yucatan",
"ZAC": "Zacatecas"
}